#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 sato Takaya <s22C1056TL@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans= 0.0
for line in sys.stdin:
    ans += float(line)

print(ans) 

*
